# escape=`

FROM microsoft/iis:windowsservercore-1803

SHELL ["powershell", "-Command", "$ErrorActionPreference = 'Stop'; $ProgressPreference = 'SilentlyContinue';"]

ARG OSPSVersion=10.0.823.0
ARG OSDEVersion=10.0.825.0

ENV OSPrivateKey=""

ENV OSController=""

ENV OSDBProvider="SQL"
ENV OSDBAuth="SQL"

ENV OSDBServer=""
ENV OSDBCatalog="outsystems"
ENV OSDBSAUser="sa"
ENV OSDBSAPass=""

ENV OSDBSessionServer=""
ENV OSDBSessionCatalog="osSession"
ENV OSDBSessionUser="OSSTATE"
ENV OSDBSessionPass=""

ENV OSDBAdminUser="OSADMIN"
ENV OSDBAdminPass=""
ENV OSDBRuntimeUser="OSRUNTIME"
ENV OSDBRuntimePass=""
ENV OSDBLogUser="OSLOG"
ENV OSDBLogPass=""

RUN Install-PackageProvider -Name NuGet -MinimumVersion 2.8.5.201 -Force; `
    Install-Module Outsystems.SetupTools -Force;

RUN Import-Module Outsystems.SetupTools; `
    Install-OSServerPreReqs -MajorVersion \"$(([System.Version]$ENV:OSPSVersion).Major).$(([System.Version]$ENV:OSPSVersion).Minor)\" -InstallIISMgmtConsole:$false; `
    Install-OSPlatformServer -Version \"$ENV:OSPSVersion\"; `
    Install-OSDevEnvironment -Version \"$ENV:OSDEVersion\"; 

COPY start.ps1 /
WORKDIR /

ENTRYPOINT []
CMD .\start.ps1 -OSPrivateKey $ENV:OSPrivateKey ` 
                -OSController $ENV:OSController `
                -OSDBProvider $ENV:OSDBProvider `
                -OSDBAuth $ENV:OSDBAuth `
                -OSDBServer $ENV:OSDBServer `
                -OSDBCatalog $ENV:OSDBCatalog `
                -OSDBSAUser $ENV:OSDBSAUser `
                -OSDBSAPass $ENV:OSDBSAPass `
                -OSDBSessionServer $ENV:OSDBSessionServer `
                -OSDBSessionCatalog $ENV:OSDBSessionCatalog `
                -OSDBSessionUser $ENV:OSDBSessionUser `
                -OSDBSessionPass $ENV:OSDBSessionPass `
                -OSDBAdminUser $ENV:OSDBAdminUser `
                -OSDBAdminPass $ENV:OSDBAdminPass `
                -OSDBRuntimeUser $ENV:OSDBRuntimeUser `
                -OSDBRuntimePass $ENV:OSDBRuntimePass `
                -OSDBLogUser $ENV:OSDBLogUser `
                -OSDBLogPass $ENV:OSDBLogPass; `